<a href="https://colab.research.google.com/github/akash648chain/metabase/blob/master/KRISH_embedding_layer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
from tensorflow.keras.preprocessing.text import one_hot

In [21]:
sent = ['the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'I am a good developer',
        'uderstand the meaning of words',
        'your videos are good',]

In [22]:
# Define the vocabulary size
voc_size = 10000

In [23]:
# one hot representation
one_hot_repr = [one_hot(words, voc_size) for words in sent]
one_hot_repr

[[1435, 5124, 5149, 3103],
 [1435, 5124, 5149, 57],
 [1435, 1288, 5149, 4446],
 [255, 9931, 136, 1321, 5644],
 [255, 9931, 136, 1321, 5268],
 [6488, 1435, 3776, 5149, 3570],
 [2493, 5256, 4106, 1321]]

In [24]:
# word embedding representations
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential


In [25]:
import numpy as np

In [26]:
sent_lenght=8
embedded_docs= pad_sequences(one_hot_repr,padding='pre',maxlen=sent_lenght)
print(embedded_docs)

[[   0    0    0    0 1435 5124 5149 3103]
 [   0    0    0    0 1435 5124 5149   57]
 [   0    0    0    0 1435 1288 5149 4446]
 [   0    0    0  255 9931  136 1321 5644]
 [   0    0    0  255 9931  136 1321 5268]
 [   0    0    0 6488 1435 3776 5149 3570]
 [   0    0    0    0 2493 5256 4106 1321]]


In [27]:
# feture representation
dim=10

In [28]:
model=Sequential()
model.add(Embedding(voc_size,dim))
model.compile('adam','mse')

In [29]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [38]:
embedded_docs[0]

array([   0,    0,    0,    0, 1435, 5124, 5149, 3103], dtype=int32)

In [32]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step


array([[[-0.01963048,  0.01555474,  0.02017016, -0.00319371,
          0.03415371,  0.00738559,  0.02357299,  0.04318393,
          0.02449012,  0.00585824],
        [-0.01963048,  0.01555474,  0.02017016, -0.00319371,
          0.03415371,  0.00738559,  0.02357299,  0.04318393,
          0.02449012,  0.00585824],
        [-0.01963048,  0.01555474,  0.02017016, -0.00319371,
          0.03415371,  0.00738559,  0.02357299,  0.04318393,
          0.02449012,  0.00585824],
        [-0.01963048,  0.01555474,  0.02017016, -0.00319371,
          0.03415371,  0.00738559,  0.02357299,  0.04318393,
          0.02449012,  0.00585824],
        [ 0.01556046,  0.04599729,  0.01733067, -0.04005086,
         -0.016072  , -0.00457826, -0.00174908,  0.03337729,
          0.02357823,  0.01977313],
        [ 0.00697969, -0.03638928, -0.00579687,  0.01379723,
          0.0089528 , -0.03924983, -0.0161337 ,  0.00489216,
         -0.03942512,  0.01053607],
        [-0.02006853,  0.00470053, -0.03662191,  0.0